site_name: About DevOps
site_url: "https://d34m0nn0n3.github.io/docs-devops/"
site_author: "Dmitriy Prigoda"

use_directory_urls: false

copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

nav:
    - DevOps: 'index.md'

plugins:
  - autolinks
  - search:
      lang:
        - en
        - ru
  - section-index
  - table-reader
  - thumbnails:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px  
  - git-revision-date-localized
  - git-revision-date
  - mermaid2
  - with-pdf:
      copyright: https://github.com/D34m0nN0n3
      cover_subtitle: ''
      output_path: DevOps.pdf

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
  - assets/mermaid.min.js
  - assets/tex-mml-chtml.js
  - assets/extra-load.js

theme:
  name: material
  custom_dir: material
  language: ru
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/favicon/favicon.png
  logo: assets/img/logo/logo.svg

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
  - markdown.extensions.attr_list 

extra:
  generator: false
  analytics:
    provider: google
    property: G-BT11X31T69
